// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: application_rpc.proto
// Protobuf C++ Version: 6.30.0

#include "application_rpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ApplicationRpcProto {

inline constexpr CommandReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        err_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CommandReply::CommandReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CommandReply_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CommandReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandReplyDefaultTypeInternal() {}
  union {
    CommandReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandReplyDefaultTypeInternal _CommandReply_default_instance_;

inline constexpr CommandArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        command_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        clientid_{::int64_t{0}},
        seqid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR CommandArgs::CommandArgs(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CommandArgs_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CommandArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandArgsDefaultTypeInternal() {}
  union {
    CommandArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandArgsDefaultTypeInternal _CommandArgs_default_instance_;
}  // namespace ApplicationRpcProto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_application_5frpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_application_5frpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_application_5frpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandArgs, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandArgs, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandArgs, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandArgs, _impl_.seqid_),
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandArgs, _impl_.command_),
        1,
        2,
        0,
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandReply, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandReply, _impl_.err_),
        PROTOBUF_FIELD_OFFSET(::ApplicationRpcProto::CommandReply, _impl_.value_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::ApplicationRpcProto::CommandArgs)},
        {14, 24, -1, sizeof(::ApplicationRpcProto::CommandReply)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::ApplicationRpcProto::_CommandArgs_default_instance_._instance,
    &::ApplicationRpcProto::_CommandReply_default_instance_._instance,
};
const char descriptor_table_protodef_application_5frpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025application_rpc.proto\022\023ApplicationRpcP"
    "roto\"\?\n\013CommandArgs\022\020\n\010ClientId\030\001 \001(\003\022\r\n"
    "\005SeqId\030\002 \001(\003\022\017\n\007Command\030\003 \001(\014\"*\n\014Command"
    "Reply\022\013\n\003Err\030\001 \001(\014\022\r\n\005Value\030\002 \001(\0142\\\n\016App"
    "licationRpc\022J\n\003Cmd\022 .ApplicationRpcProto"
    ".CommandArgs\032!.ApplicationRpcProto.Comma"
    "ndReplyb\006proto3"
};
static ::absl::once_flag descriptor_table_application_5frpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_application_5frpc_2eproto = {
    false,
    false,
    255,
    descriptor_table_protodef_application_5frpc_2eproto,
    "application_rpc.proto",
    &descriptor_table_application_5frpc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_application_5frpc_2eproto::offsets,
    file_level_enum_descriptors_application_5frpc_2eproto,
    file_level_service_descriptors_application_5frpc_2eproto,
};
namespace ApplicationRpcProto {
// ===================================================================

class CommandArgs::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CommandArgs>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_._has_bits_);
};

CommandArgs::CommandArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CommandArgs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ApplicationRpcProto.CommandArgs)
}
PROTOBUF_NDEBUG_INLINE CommandArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ApplicationRpcProto::CommandArgs& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        command_(arena, from.command_) {}

CommandArgs::CommandArgs(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CommandArgs& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CommandArgs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CommandArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, clientid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, clientid_),
           offsetof(Impl_, seqid_) -
               offsetof(Impl_, clientid_) +
               sizeof(Impl_::seqid_));

  // @@protoc_insertion_point(copy_constructor:ApplicationRpcProto.CommandArgs)
}
PROTOBUF_NDEBUG_INLINE CommandArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        command_(arena) {}

inline void CommandArgs::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, clientid_),
           0,
           offsetof(Impl_, seqid_) -
               offsetof(Impl_, clientid_) +
               sizeof(Impl_::seqid_));
}
CommandArgs::~CommandArgs() {
  // @@protoc_insertion_point(destructor:ApplicationRpcProto.CommandArgs)
  SharedDtor(*this);
}
inline void CommandArgs::SharedDtor(MessageLite& self) {
  CommandArgs& this_ = static_cast<CommandArgs&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.command_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CommandArgs::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CommandArgs(arena);
}
constexpr auto CommandArgs::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CommandArgs),
                                            alignof(CommandArgs));
}
constexpr auto CommandArgs::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CommandArgs_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CommandArgs::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CommandArgs>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CommandArgs::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CommandArgs>(), &CommandArgs::ByteSizeLong,
              &CommandArgs::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_._cached_size_),
          false,
      },
      &CommandArgs::kDescriptorMethods,
      &descriptor_table_application_5frpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        CommandArgs_class_data_ =
            CommandArgs::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL CommandArgs::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CommandArgs_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CommandArgs_class_data_.tc_table);
  return CommandArgs_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
CommandArgs::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CommandArgs_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ApplicationRpcProto::CommandArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 ClientId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CommandArgs, _impl_.clientid_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.clientid_)}},
    // int64 SeqId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CommandArgs, _impl_.seqid_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.seqid_)}},
    // bytes Command = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.command_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 ClientId = 1;
    {PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.clientid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 SeqId = 2;
    {PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.seqid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // bytes Command = 3;
    {PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.command_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CommandArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:ApplicationRpcProto.CommandArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.command_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006u) != 0) {
    ::memset(&_impl_.clientid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.seqid_) -
        reinterpret_cast<char*>(&_impl_.clientid_)) + sizeof(_impl_.seqid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CommandArgs::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CommandArgs& this_ = static_cast<const CommandArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CommandArgs::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CommandArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ApplicationRpcProto.CommandArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 ClientId = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_clientid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_clientid(), target);
    }
  }

  // int64 SeqId = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_seqid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_seqid(), target);
    }
  }

  // bytes Command = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_command().empty()) {
      const std::string& _s = this_._internal_command();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ApplicationRpcProto.CommandArgs)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CommandArgs::ByteSizeLong(const MessageLite& base) {
  const CommandArgs& this_ = static_cast<const CommandArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CommandArgs::ByteSizeLong() const {
  const CommandArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ApplicationRpcProto.CommandArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // bytes Command = 3;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_command().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_command());
      }
    }
    // int64 ClientId = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_clientid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_clientid());
      }
    }
    // int64 SeqId = 2;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_seqid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_seqid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CommandArgs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CommandArgs*>(&to_msg);
  auto& from = static_cast<const CommandArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ApplicationRpcProto.CommandArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_command().empty()) {
        _this->_internal_set_command(from._internal_command());
      } else {
        if (_this->_impl_.command_.IsDefault()) {
          _this->_internal_set_command("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_clientid() != 0) {
        _this->_impl_.clientid_ = from._impl_.clientid_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_seqid() != 0) {
        _this->_impl_.seqid_ = from._impl_.seqid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommandArgs::CopyFrom(const CommandArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ApplicationRpcProto.CommandArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommandArgs::InternalSwap(CommandArgs* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.command_, &other->_impl_.command_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.seqid_)
      + sizeof(CommandArgs::_impl_.seqid_)
      - PROTOBUF_FIELD_OFFSET(CommandArgs, _impl_.clientid_)>(
          reinterpret_cast<char*>(&_impl_.clientid_),
          reinterpret_cast<char*>(&other->_impl_.clientid_));
}

::google::protobuf::Metadata CommandArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CommandReply::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CommandReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CommandReply, _impl_._has_bits_);
};

CommandReply::CommandReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CommandReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ApplicationRpcProto.CommandReply)
}
PROTOBUF_NDEBUG_INLINE CommandReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ApplicationRpcProto::CommandReply& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        err_(arena, from.err_),
        value_(arena, from.value_) {}

CommandReply::CommandReply(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CommandReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CommandReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CommandReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ApplicationRpcProto.CommandReply)
}
PROTOBUF_NDEBUG_INLINE CommandReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        err_(arena),
        value_(arena) {}

inline void CommandReply::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CommandReply::~CommandReply() {
  // @@protoc_insertion_point(destructor:ApplicationRpcProto.CommandReply)
  SharedDtor(*this);
}
inline void CommandReply::SharedDtor(MessageLite& self) {
  CommandReply& this_ = static_cast<CommandReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.err_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CommandReply::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CommandReply(arena);
}
constexpr auto CommandReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CommandReply),
                                            alignof(CommandReply));
}
constexpr auto CommandReply::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CommandReply_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CommandReply::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CommandReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CommandReply::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CommandReply>(), &CommandReply::ByteSizeLong,
              &CommandReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CommandReply, _impl_._cached_size_),
          false,
      },
      &CommandReply::kDescriptorMethods,
      &descriptor_table_application_5frpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        CommandReply_class_data_ =
            CommandReply::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL CommandReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CommandReply_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CommandReply_class_data_.tc_table);
  return CommandReply_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
CommandReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CommandReply, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CommandReply_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ApplicationRpcProto::CommandReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes Value = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(CommandReply, _impl_.value_)}},
    // bytes Err = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CommandReply, _impl_.err_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes Err = 1;
    {PROTOBUF_FIELD_OFFSET(CommandReply, _impl_.err_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes Value = 2;
    {PROTOBUF_FIELD_OFFSET(CommandReply, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CommandReply::Clear() {
// @@protoc_insertion_point(message_clear_start:ApplicationRpcProto.CommandReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.err_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CommandReply::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CommandReply& this_ = static_cast<const CommandReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CommandReply::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CommandReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ApplicationRpcProto.CommandReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes Err = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_err().empty()) {
      const std::string& _s = this_._internal_err();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes Value = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_value().empty()) {
      const std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ApplicationRpcProto.CommandReply)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CommandReply::ByteSizeLong(const MessageLite& base) {
  const CommandReply& this_ = static_cast<const CommandReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CommandReply::ByteSizeLong() const {
  const CommandReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ApplicationRpcProto.CommandReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // bytes Err = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_err().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_err());
      }
    }
    // bytes Value = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CommandReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CommandReply*>(&to_msg);
  auto& from = static_cast<const CommandReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ApplicationRpcProto.CommandReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_err().empty()) {
        _this->_internal_set_err(from._internal_err());
      } else {
        if (_this->_impl_.err_.IsDefault()) {
          _this->_internal_set_err("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommandReply::CopyFrom(const CommandReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ApplicationRpcProto.CommandReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommandReply::InternalSwap(CommandReply* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.err_, &other->_impl_.err_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata CommandReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ApplicationRpcProto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_application_5frpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
