// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: application_rpc.proto

#include "application_rpc.pb.h"
#include "application_rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ApplicationRpcProto {

static const char* ApplicationRpc_method_names[] = {
  "/ApplicationRpcProto.ApplicationRpc/Cmd",
};

std::unique_ptr< ApplicationRpc::Stub> ApplicationRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ApplicationRpc::Stub> stub(new ApplicationRpc::Stub(channel, options));
  return stub;
}

ApplicationRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Cmd_(ApplicationRpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ApplicationRpc::Stub::Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::ApplicationRpcProto::CommandReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Cmd_, context, request, response);
}

void ApplicationRpc::Stub::async::Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Cmd_, context, request, response, std::move(f));
}

void ApplicationRpc::Stub::async::Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Cmd_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>* ApplicationRpc::Stub::PrepareAsyncCmdRaw(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ApplicationRpcProto::CommandReply, ::ApplicationRpcProto::CommandArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Cmd_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>* ApplicationRpc::Stub::AsyncCmdRaw(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCmdRaw(context, request, cq);
  result->StartCall();
  return result;
}

ApplicationRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApplicationRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApplicationRpc::Service, ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApplicationRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ApplicationRpcProto::CommandArgs* req,
             ::ApplicationRpcProto::CommandReply* resp) {
               return service->Cmd(ctx, req, resp);
             }, this)));
}

ApplicationRpc::Service::~Service() {
}

::grpc::Status ApplicationRpc::Service::Cmd(::grpc::ServerContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ApplicationRpcProto

