// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: application_rpc.proto
#ifndef GRPC_application_5frpc_2eproto__INCLUDED
#define GRPC_application_5frpc_2eproto__INCLUDED

#include "application_rpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace ApplicationRpcProto {

class ApplicationRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "ApplicationRpcProto.ApplicationRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::ApplicationRpcProto::CommandReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationRpcProto::CommandReply>> AsyncCmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationRpcProto::CommandReply>>(AsyncCmdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationRpcProto::CommandReply>> PrepareAsyncCmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationRpcProto::CommandReply>>(PrepareAsyncCmdRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationRpcProto::CommandReply>* AsyncCmdRaw(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationRpcProto::CommandReply>* PrepareAsyncCmdRaw(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::ApplicationRpcProto::CommandReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>> AsyncCmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>>(AsyncCmdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>> PrepareAsyncCmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>>(PrepareAsyncCmdRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response, std::function<void(::grpc::Status)>) override;
      void Cmd(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>* AsyncCmdRaw(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ApplicationRpcProto::CommandReply>* PrepareAsyncCmdRaw(::grpc::ClientContext* context, const ::ApplicationRpcProto::CommandArgs& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Cmd_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Cmd(::grpc::ServerContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Cmd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Cmd() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Cmd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cmd(::grpc::ServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCmd(::grpc::ServerContext* context, ::ApplicationRpcProto::CommandArgs* request, ::grpc::ServerAsyncResponseWriter< ::ApplicationRpcProto::CommandReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Cmd<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Cmd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Cmd() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ApplicationRpcProto::CommandArgs* request, ::ApplicationRpcProto::CommandReply* response) { return this->Cmd(context, request, response); }));}
    void SetMessageAllocatorFor_Cmd(
        ::grpc::MessageAllocator< ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Cmd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cmd(::grpc::ServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Cmd(
      ::grpc::CallbackServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Cmd<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Cmd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Cmd() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Cmd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cmd(::grpc::ServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Cmd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Cmd() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Cmd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cmd(::grpc::ServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCmd(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Cmd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Cmd() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Cmd(context, request, response); }));
    }
    ~WithRawCallbackMethod_Cmd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Cmd(::grpc::ServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Cmd(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Cmd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Cmd() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ApplicationRpcProto::CommandArgs, ::ApplicationRpcProto::CommandReply>* streamer) {
                       return this->StreamedCmd(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Cmd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Cmd(::grpc::ServerContext* /*context*/, const ::ApplicationRpcProto::CommandArgs* /*request*/, ::ApplicationRpcProto::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCmd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ApplicationRpcProto::CommandArgs,::ApplicationRpcProto::CommandReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Cmd<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Cmd<Service > StreamedService;
};

}  // namespace ApplicationRpcProto


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_application_5frpc_2eproto__INCLUDED
