// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: application_rpc.proto
// Protobuf C++ Version: 6.30.0

#ifndef application_5frpc_2eproto_2epb_2eh
#define application_5frpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_application_5frpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_application_5frpc_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_application_5frpc_2eproto;
}  // extern "C"
namespace ApplicationRpcProto {
class CommandArgs;
struct CommandArgsDefaultTypeInternal;
extern CommandArgsDefaultTypeInternal _CommandArgs_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CommandArgs_class_data_;
class CommandReply;
struct CommandReplyDefaultTypeInternal;
extern CommandReplyDefaultTypeInternal _CommandReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CommandReply_class_data_;
}  // namespace ApplicationRpcProto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ApplicationRpcProto {

// ===================================================================


// -------------------------------------------------------------------

class CommandReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ApplicationRpcProto.CommandReply) */ {
 public:
  inline CommandReply() : CommandReply(nullptr) {}
  ~CommandReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CommandReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CommandReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CommandReply(::google::protobuf::internal::ConstantInitialized);

  inline CommandReply(const CommandReply& from) : CommandReply(nullptr, from) {}
  inline CommandReply(CommandReply&& from) noexcept
      : CommandReply(nullptr, std::move(from)) {}
  inline CommandReply& operator=(const CommandReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline CommandReply& operator=(CommandReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CommandReply& default_instance() {
    return *reinterpret_cast<const CommandReply*>(
        &_CommandReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CommandReply& a, CommandReply& b) { a.Swap(&b); }
  inline void Swap(CommandReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CommandReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CommandReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CommandReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CommandReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CommandReply& from) { CommandReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CommandReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ApplicationRpcProto.CommandReply"; }

 protected:
  explicit CommandReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CommandReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CommandReply& from);
  CommandReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CommandReply&& from) noexcept
      : CommandReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // bytes Err = 1;
  void clear_err() ;
  const std::string& err() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_err(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_err();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_err();
  void set_allocated_err(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_err() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_err(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_err();

  public:
  // bytes Value = 2;
  void clear_value() ;
  const std::string& value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // @@protoc_insertion_point(class_scope:ApplicationRpcProto.CommandReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CommandReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr err_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_application_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CommandReply_class_data_;
// -------------------------------------------------------------------

class CommandArgs final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ApplicationRpcProto.CommandArgs) */ {
 public:
  inline CommandArgs() : CommandArgs(nullptr) {}
  ~CommandArgs() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CommandArgs* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CommandArgs));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CommandArgs(::google::protobuf::internal::ConstantInitialized);

  inline CommandArgs(const CommandArgs& from) : CommandArgs(nullptr, from) {}
  inline CommandArgs(CommandArgs&& from) noexcept
      : CommandArgs(nullptr, std::move(from)) {}
  inline CommandArgs& operator=(const CommandArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline CommandArgs& operator=(CommandArgs&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CommandArgs& default_instance() {
    return *reinterpret_cast<const CommandArgs*>(
        &_CommandArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CommandArgs& a, CommandArgs& b) { a.Swap(&b); }
  inline void Swap(CommandArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CommandArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CommandArgs* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CommandArgs>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CommandArgs& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CommandArgs& from) { CommandArgs::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CommandArgs* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ApplicationRpcProto.CommandArgs"; }

 protected:
  explicit CommandArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CommandArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CommandArgs& from);
  CommandArgs(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CommandArgs&& from) noexcept
      : CommandArgs(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandFieldNumber = 3,
    kClientIdFieldNumber = 1,
    kSeqIdFieldNumber = 2,
  };
  // bytes Command = 3;
  void clear_command() ;
  const std::string& command() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_command(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_command();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_command();
  void set_allocated_command(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_command() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_command();

  public:
  // int64 ClientId = 1;
  void clear_clientid() ;
  ::int64_t clientid() const;
  void set_clientid(::int64_t value);

  private:
  ::int64_t _internal_clientid() const;
  void _internal_set_clientid(::int64_t value);

  public:
  // int64 SeqId = 2;
  void clear_seqid() ;
  ::int64_t seqid() const;
  void set_seqid(::int64_t value);

  private:
  ::int64_t _internal_seqid() const;
  void _internal_set_seqid(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:ApplicationRpcProto.CommandArgs)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CommandArgs& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr command_;
    ::int64_t clientid_;
    ::int64_t seqid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_application_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CommandArgs_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CommandArgs

// int64 ClientId = 1;
inline void CommandArgs::clear_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t CommandArgs::clientid() const {
  // @@protoc_insertion_point(field_get:ApplicationRpcProto.CommandArgs.ClientId)
  return _internal_clientid();
}
inline void CommandArgs::set_clientid(::int64_t value) {
  _internal_set_clientid(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ApplicationRpcProto.CommandArgs.ClientId)
}
inline ::int64_t CommandArgs::_internal_clientid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientid_;
}
inline void CommandArgs::_internal_set_clientid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_ = value;
}

// int64 SeqId = 2;
inline void CommandArgs::clear_seqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seqid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t CommandArgs::seqid() const {
  // @@protoc_insertion_point(field_get:ApplicationRpcProto.CommandArgs.SeqId)
  return _internal_seqid();
}
inline void CommandArgs::set_seqid(::int64_t value) {
  _internal_set_seqid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ApplicationRpcProto.CommandArgs.SeqId)
}
inline ::int64_t CommandArgs::_internal_seqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seqid_;
}
inline void CommandArgs::_internal_set_seqid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seqid_ = value;
}

// bytes Command = 3;
inline void CommandArgs::clear_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CommandArgs::command() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ApplicationRpcProto.CommandArgs.Command)
  return _internal_command();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CommandArgs::set_command(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.command_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ApplicationRpcProto.CommandArgs.Command)
}
inline std::string* PROTOBUF_NONNULL CommandArgs::mutable_command()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:ApplicationRpcProto.CommandArgs.Command)
  return _s;
}
inline const std::string& CommandArgs::_internal_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.command_.Get();
}
inline void CommandArgs::_internal_set_command(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.command_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL CommandArgs::_internal_mutable_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.command_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE CommandArgs::release_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ApplicationRpcProto.CommandArgs.Command)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.command_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.command_.Set("", GetArena());
  }
  return released;
}
inline void CommandArgs::set_allocated_command(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.command_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ApplicationRpcProto.CommandArgs.Command)
}

// -------------------------------------------------------------------

// CommandReply

// bytes Err = 1;
inline void CommandReply::clear_err() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.err_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CommandReply::err() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ApplicationRpcProto.CommandReply.Err)
  return _internal_err();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CommandReply::set_err(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.err_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ApplicationRpcProto.CommandReply.Err)
}
inline std::string* PROTOBUF_NONNULL CommandReply::mutable_err()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_err();
  // @@protoc_insertion_point(field_mutable:ApplicationRpcProto.CommandReply.Err)
  return _s;
}
inline const std::string& CommandReply::_internal_err() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.err_.Get();
}
inline void CommandReply::_internal_set_err(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.err_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL CommandReply::_internal_mutable_err() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.err_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE CommandReply::release_err() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ApplicationRpcProto.CommandReply.Err)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.err_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.err_.Set("", GetArena());
  }
  return released;
}
inline void CommandReply::set_allocated_err(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.err_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.err_.IsDefault()) {
    _impl_.err_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ApplicationRpcProto.CommandReply.Err)
}

// bytes Value = 2;
inline void CommandReply::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CommandReply::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ApplicationRpcProto.CommandReply.Value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CommandReply::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ApplicationRpcProto.CommandReply.Value)
}
inline std::string* PROTOBUF_NONNULL CommandReply::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:ApplicationRpcProto.CommandReply.Value)
  return _s;
}
inline const std::string& CommandReply::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void CommandReply::_internal_set_value(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL CommandReply::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.value_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE CommandReply::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ApplicationRpcProto.CommandReply.Value)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void CommandReply::set_allocated_value(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ApplicationRpcProto.CommandReply.Value)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ApplicationRpcProto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // application_5frpc_2eproto_2epb_2eh
