// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: raft_node_rpc.proto
// Protobuf C++ Version: 6.30.0

#ifndef raft_5fnode_5frpc_2eproto_2epb_2eh
#define raft_5fnode_5frpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_raft_5fnode_5frpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_raft_5fnode_5frpc_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_raft_5fnode_5frpc_2eproto;
}  // extern "C"
namespace RaftNodeRpcProtoc {
class AppendEntriesArgs;
struct AppendEntriesArgsDefaultTypeInternal;
extern AppendEntriesArgsDefaultTypeInternal _AppendEntriesArgs_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AppendEntriesArgs_class_data_;
class AppendEntriesReply;
struct AppendEntriesReplyDefaultTypeInternal;
extern AppendEntriesReplyDefaultTypeInternal _AppendEntriesReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AppendEntriesReply_class_data_;
class InstallSnapshotArgs;
struct InstallSnapshotArgsDefaultTypeInternal;
extern InstallSnapshotArgsDefaultTypeInternal _InstallSnapshotArgs_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InstallSnapshotArgs_class_data_;
class InstallSnapshotReply;
struct InstallSnapshotReplyDefaultTypeInternal;
extern InstallSnapshotReplyDefaultTypeInternal _InstallSnapshotReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InstallSnapshotReply_class_data_;
class LogEntry;
struct LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LogEntry_class_data_;
class RequestVoteArgs;
struct RequestVoteArgsDefaultTypeInternal;
extern RequestVoteArgsDefaultTypeInternal _RequestVoteArgs_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RequestVoteArgs_class_data_;
class RequestVoteReply;
struct RequestVoteReplyDefaultTypeInternal;
extern RequestVoteReplyDefaultTypeInternal _RequestVoteReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RequestVoteReply_class_data_;
}  // namespace RaftNodeRpcProtoc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace RaftNodeRpcProtoc {

// ===================================================================


// -------------------------------------------------------------------

class RequestVoteReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.RequestVoteReply) */ {
 public:
  inline RequestVoteReply() : RequestVoteReply(nullptr) {}
  ~RequestVoteReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestVoteReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestVoteReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestVoteReply(::google::protobuf::internal::ConstantInitialized);

  inline RequestVoteReply(const RequestVoteReply& from) : RequestVoteReply(nullptr, from) {}
  inline RequestVoteReply(RequestVoteReply&& from) noexcept
      : RequestVoteReply(nullptr, std::move(from)) {}
  inline RequestVoteReply& operator=(const RequestVoteReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteReply& operator=(RequestVoteReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteReply& default_instance() {
    return *reinterpret_cast<const RequestVoteReply*>(
        &_RequestVoteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(RequestVoteReply& a, RequestVoteReply& b) { a.Swap(&b); }
  inline void Swap(RequestVoteReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestVoteReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestVoteReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestVoteReply& from) { RequestVoteReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestVoteReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.RequestVoteReply"; }

 protected:
  explicit RequestVoteReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RequestVoteReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RequestVoteReply& from);
  RequestVoteReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RequestVoteReply&& from) noexcept
      : RequestVoteReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kVoteStateFieldNumber = 3,
    kVoteGrantedFieldNumber = 2,
  };
  // int64 Term = 1;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // int64 VoteState = 3;
  void clear_votestate() ;
  ::int64_t votestate() const;
  void set_votestate(::int64_t value);

  private:
  ::int64_t _internal_votestate() const;
  void _internal_set_votestate(::int64_t value);

  public:
  // bool VoteGranted = 2;
  void clear_votegranted() ;
  bool votegranted() const;
  void set_votegranted(bool value);

  private:
  bool _internal_votegranted() const;
  void _internal_set_votegranted(bool value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.RequestVoteReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RequestVoteReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t term_;
    ::int64_t votestate_;
    bool votegranted_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RequestVoteReply_class_data_;
// -------------------------------------------------------------------

class RequestVoteArgs final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.RequestVoteArgs) */ {
 public:
  inline RequestVoteArgs() : RequestVoteArgs(nullptr) {}
  ~RequestVoteArgs() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestVoteArgs* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestVoteArgs));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestVoteArgs(::google::protobuf::internal::ConstantInitialized);

  inline RequestVoteArgs(const RequestVoteArgs& from) : RequestVoteArgs(nullptr, from) {}
  inline RequestVoteArgs(RequestVoteArgs&& from) noexcept
      : RequestVoteArgs(nullptr, std::move(from)) {}
  inline RequestVoteArgs& operator=(const RequestVoteArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteArgs& operator=(RequestVoteArgs&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteArgs& default_instance() {
    return *reinterpret_cast<const RequestVoteArgs*>(
        &_RequestVoteArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RequestVoteArgs& a, RequestVoteArgs& b) { a.Swap(&b); }
  inline void Swap(RequestVoteArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteArgs* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestVoteArgs>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestVoteArgs& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestVoteArgs& from) { RequestVoteArgs::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestVoteArgs* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.RequestVoteArgs"; }

 protected:
  explicit RequestVoteArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RequestVoteArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RequestVoteArgs& from);
  RequestVoteArgs(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RequestVoteArgs&& from) noexcept
      : RequestVoteArgs(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kCandidateIdFieldNumber = 2,
    kLastLogIndexFieldNumber = 3,
    kLastLogTermFieldNumber = 4,
  };
  // int64 Term = 1;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // int64 CandidateId = 2;
  void clear_candidateid() ;
  ::int64_t candidateid() const;
  void set_candidateid(::int64_t value);

  private:
  ::int64_t _internal_candidateid() const;
  void _internal_set_candidateid(::int64_t value);

  public:
  // int64 LastLogIndex = 3;
  void clear_lastlogindex() ;
  ::int64_t lastlogindex() const;
  void set_lastlogindex(::int64_t value);

  private:
  ::int64_t _internal_lastlogindex() const;
  void _internal_set_lastlogindex(::int64_t value);

  public:
  // int64 LastLogTerm = 4;
  void clear_lastlogterm() ;
  ::int64_t lastlogterm() const;
  void set_lastlogterm(::int64_t value);

  private:
  ::int64_t _internal_lastlogterm() const;
  void _internal_set_lastlogterm(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.RequestVoteArgs)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RequestVoteArgs& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t term_;
    ::int64_t candidateid_;
    ::int64_t lastlogindex_;
    ::int64_t lastlogterm_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RequestVoteArgs_class_data_;
// -------------------------------------------------------------------

class LogEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.LogEntry) */ {
 public:
  inline LogEntry() : LogEntry(nullptr) {}
  ~LogEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LogEntry* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LogEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LogEntry(::google::protobuf::internal::ConstantInitialized);

  inline LogEntry(const LogEntry& from) : LogEntry(nullptr, from) {}
  inline LogEntry(LogEntry&& from) noexcept
      : LogEntry(nullptr, std::move(from)) {}
  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogEntry& default_instance() {
    return *reinterpret_cast<const LogEntry*>(
        &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LogEntry& a, LogEntry& b) { a.Swap(&b); }
  inline void Swap(LogEntry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogEntry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogEntry* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LogEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LogEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LogEntry& from) { LogEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LogEntry* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.LogEntry"; }

 protected:
  explicit LogEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LogEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LogEntry& from);
  LogEntry(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LogEntry&& from) noexcept
      : LogEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandFieldNumber = 1,
    kLogIndexFieldNumber = 2,
    kLogTermFieldNumber = 3,
  };
  // bytes Command = 1;
  void clear_command() ;
  const std::string& command() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_command(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_command();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_command();
  void set_allocated_command(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_command() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_command();

  public:
  // int64 LogIndex = 2;
  void clear_logindex() ;
  ::int64_t logindex() const;
  void set_logindex(::int64_t value);

  private:
  ::int64_t _internal_logindex() const;
  void _internal_set_logindex(::int64_t value);

  public:
  // int64 LogTerm = 3;
  void clear_logterm() ;
  ::int64_t logterm() const;
  void set_logterm(::int64_t value);

  private:
  ::int64_t _internal_logterm() const;
  void _internal_set_logterm(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.LogEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LogEntry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr command_;
    ::int64_t logindex_;
    ::int64_t logterm_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LogEntry_class_data_;
// -------------------------------------------------------------------

class InstallSnapshotReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.InstallSnapshotReply) */ {
 public:
  inline InstallSnapshotReply() : InstallSnapshotReply(nullptr) {}
  ~InstallSnapshotReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InstallSnapshotReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InstallSnapshotReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InstallSnapshotReply(::google::protobuf::internal::ConstantInitialized);

  inline InstallSnapshotReply(const InstallSnapshotReply& from) : InstallSnapshotReply(nullptr, from) {}
  inline InstallSnapshotReply(InstallSnapshotReply&& from) noexcept
      : InstallSnapshotReply(nullptr, std::move(from)) {}
  inline InstallSnapshotReply& operator=(const InstallSnapshotReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallSnapshotReply& operator=(InstallSnapshotReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstallSnapshotReply& default_instance() {
    return *reinterpret_cast<const InstallSnapshotReply*>(
        &_InstallSnapshotReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(InstallSnapshotReply& a, InstallSnapshotReply& b) { a.Swap(&b); }
  inline void Swap(InstallSnapshotReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallSnapshotReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallSnapshotReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InstallSnapshotReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InstallSnapshotReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InstallSnapshotReply& from) { InstallSnapshotReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InstallSnapshotReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.InstallSnapshotReply"; }

 protected:
  explicit InstallSnapshotReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InstallSnapshotReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InstallSnapshotReply& from);
  InstallSnapshotReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InstallSnapshotReply&& from) noexcept
      : InstallSnapshotReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kSuccessFieldNumber = 2,
  };
  // int64 Term = 1;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // bool Success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.InstallSnapshotReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InstallSnapshotReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t term_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InstallSnapshotReply_class_data_;
// -------------------------------------------------------------------

class InstallSnapshotArgs final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.InstallSnapshotArgs) */ {
 public:
  inline InstallSnapshotArgs() : InstallSnapshotArgs(nullptr) {}
  ~InstallSnapshotArgs() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InstallSnapshotArgs* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InstallSnapshotArgs));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InstallSnapshotArgs(::google::protobuf::internal::ConstantInitialized);

  inline InstallSnapshotArgs(const InstallSnapshotArgs& from) : InstallSnapshotArgs(nullptr, from) {}
  inline InstallSnapshotArgs(InstallSnapshotArgs&& from) noexcept
      : InstallSnapshotArgs(nullptr, std::move(from)) {}
  inline InstallSnapshotArgs& operator=(const InstallSnapshotArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallSnapshotArgs& operator=(InstallSnapshotArgs&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstallSnapshotArgs& default_instance() {
    return *reinterpret_cast<const InstallSnapshotArgs*>(
        &_InstallSnapshotArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(InstallSnapshotArgs& a, InstallSnapshotArgs& b) { a.Swap(&b); }
  inline void Swap(InstallSnapshotArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallSnapshotArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallSnapshotArgs* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InstallSnapshotArgs>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InstallSnapshotArgs& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InstallSnapshotArgs& from) { InstallSnapshotArgs::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InstallSnapshotArgs* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.InstallSnapshotArgs"; }

 protected:
  explicit InstallSnapshotArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InstallSnapshotArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InstallSnapshotArgs& from);
  InstallSnapshotArgs(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InstallSnapshotArgs&& from) noexcept
      : InstallSnapshotArgs(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSnapshotFieldNumber = 6,
    kTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kLastIncludedIndexFieldNumber = 4,
    kLastIncludedTermFieldNumber = 5,
  };
  // bytes Snapshot = 6;
  void clear_snapshot() ;
  const std::string& snapshot() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_snapshot(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_snapshot();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_snapshot();
  void set_allocated_snapshot(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_snapshot() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_snapshot(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_snapshot();

  public:
  // int64 Term = 1;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // int64 LeaderId = 2;
  void clear_leaderid() ;
  ::int64_t leaderid() const;
  void set_leaderid(::int64_t value);

  private:
  ::int64_t _internal_leaderid() const;
  void _internal_set_leaderid(::int64_t value);

  public:
  // int64 LastIncludedIndex = 4;
  void clear_lastincludedindex() ;
  ::int64_t lastincludedindex() const;
  void set_lastincludedindex(::int64_t value);

  private:
  ::int64_t _internal_lastincludedindex() const;
  void _internal_set_lastincludedindex(::int64_t value);

  public:
  // int64 LastIncludedTerm = 5;
  void clear_lastincludedterm() ;
  ::int64_t lastincludedterm() const;
  void set_lastincludedterm(::int64_t value);

  private:
  ::int64_t _internal_lastincludedterm() const;
  void _internal_set_lastincludedterm(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.InstallSnapshotArgs)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InstallSnapshotArgs& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr snapshot_;
    ::int64_t term_;
    ::int64_t leaderid_;
    ::int64_t lastincludedindex_;
    ::int64_t lastincludedterm_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InstallSnapshotArgs_class_data_;
// -------------------------------------------------------------------

class AppendEntriesReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.AppendEntriesReply) */ {
 public:
  inline AppendEntriesReply() : AppendEntriesReply(nullptr) {}
  ~AppendEntriesReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AppendEntriesReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AppendEntriesReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AppendEntriesReply(::google::protobuf::internal::ConstantInitialized);

  inline AppendEntriesReply(const AppendEntriesReply& from) : AppendEntriesReply(nullptr, from) {}
  inline AppendEntriesReply(AppendEntriesReply&& from) noexcept
      : AppendEntriesReply(nullptr, std::move(from)) {}
  inline AppendEntriesReply& operator=(const AppendEntriesReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesReply& operator=(AppendEntriesReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesReply& default_instance() {
    return *reinterpret_cast<const AppendEntriesReply*>(
        &_AppendEntriesReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AppendEntriesReply& a, AppendEntriesReply& b) { a.Swap(&b); }
  inline void Swap(AppendEntriesReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AppendEntriesReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AppendEntriesReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AppendEntriesReply& from) { AppendEntriesReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AppendEntriesReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.AppendEntriesReply"; }

 protected:
  explicit AppendEntriesReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AppendEntriesReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AppendEntriesReply& from);
  AppendEntriesReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AppendEntriesReply&& from) noexcept
      : AppendEntriesReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kNextIndexFieldNumber = 2,
    kNodeStateFieldNumber = 4,
    kSuccessFieldNumber = 3,
  };
  // int64 Term = 1;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // int64 NextIndex = 2;
  void clear_nextindex() ;
  ::int64_t nextindex() const;
  void set_nextindex(::int64_t value);

  private:
  ::int64_t _internal_nextindex() const;
  void _internal_set_nextindex(::int64_t value);

  public:
  // int64 NodeState = 4;
  void clear_nodestate() ;
  ::int64_t nodestate() const;
  void set_nodestate(::int64_t value);

  private:
  ::int64_t _internal_nodestate() const;
  void _internal_set_nodestate(::int64_t value);

  public:
  // bool Success = 3;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.AppendEntriesReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AppendEntriesReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t term_;
    ::int64_t nextindex_;
    ::int64_t nodestate_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AppendEntriesReply_class_data_;
// -------------------------------------------------------------------

class AppendEntriesArgs final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RaftNodeRpcProtoc.AppendEntriesArgs) */ {
 public:
  inline AppendEntriesArgs() : AppendEntriesArgs(nullptr) {}
  ~AppendEntriesArgs() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AppendEntriesArgs* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AppendEntriesArgs));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AppendEntriesArgs(::google::protobuf::internal::ConstantInitialized);

  inline AppendEntriesArgs(const AppendEntriesArgs& from) : AppendEntriesArgs(nullptr, from) {}
  inline AppendEntriesArgs(AppendEntriesArgs&& from) noexcept
      : AppendEntriesArgs(nullptr, std::move(from)) {}
  inline AppendEntriesArgs& operator=(const AppendEntriesArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesArgs& operator=(AppendEntriesArgs&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesArgs& default_instance() {
    return *reinterpret_cast<const AppendEntriesArgs*>(
        &_AppendEntriesArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AppendEntriesArgs& a, AppendEntriesArgs& b) { a.Swap(&b); }
  inline void Swap(AppendEntriesArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesArgs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesArgs* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AppendEntriesArgs>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AppendEntriesArgs& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AppendEntriesArgs& from) { AppendEntriesArgs::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AppendEntriesArgs* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RaftNodeRpcProtoc.AppendEntriesArgs"; }

 protected:
  explicit AppendEntriesArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AppendEntriesArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AppendEntriesArgs& from);
  AppendEntriesArgs(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AppendEntriesArgs&& from) noexcept
      : AppendEntriesArgs(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEntriesFieldNumber = 5,
    kCurTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kPrevLogIndexFieldNumber = 3,
    kPrevLogTermFieldNumber = 4,
    kLeaderCommitIndexFieldNumber = 6,
  };
  // repeated .RaftNodeRpcProtoc.LogEntry Entries = 5;
  int entries_size() const;
  private:
  int _internal_entries_size() const;

  public:
  void clear_entries() ;
  ::RaftNodeRpcProtoc::LogEntry* PROTOBUF_NONNULL mutable_entries(int index);
  ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>* PROTOBUF_NONNULL mutable_entries();

  private:
  const ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>& _internal_entries() const;
  ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>* PROTOBUF_NONNULL _internal_mutable_entries();
  public:
  const ::RaftNodeRpcProtoc::LogEntry& entries(int index) const;
  ::RaftNodeRpcProtoc::LogEntry* PROTOBUF_NONNULL add_entries();
  const ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>& entries() const;
  // int64 CurTerm = 1;
  void clear_curterm() ;
  ::int64_t curterm() const;
  void set_curterm(::int64_t value);

  private:
  ::int64_t _internal_curterm() const;
  void _internal_set_curterm(::int64_t value);

  public:
  // int64 LeaderId = 2;
  void clear_leaderid() ;
  ::int64_t leaderid() const;
  void set_leaderid(::int64_t value);

  private:
  ::int64_t _internal_leaderid() const;
  void _internal_set_leaderid(::int64_t value);

  public:
  // int64 PrevLogIndex = 3;
  void clear_prevlogindex() ;
  ::int64_t prevlogindex() const;
  void set_prevlogindex(::int64_t value);

  private:
  ::int64_t _internal_prevlogindex() const;
  void _internal_set_prevlogindex(::int64_t value);

  public:
  // int64 PrevLogTerm = 4;
  void clear_prevlogterm() ;
  ::int64_t prevlogterm() const;
  void set_prevlogterm(::int64_t value);

  private:
  ::int64_t _internal_prevlogterm() const;
  void _internal_set_prevlogterm(::int64_t value);

  public:
  // int64 LeaderCommitIndex = 6;
  void clear_leadercommitindex() ;
  ::int64_t leadercommitindex() const;
  void set_leadercommitindex(::int64_t value);

  private:
  ::int64_t _internal_leadercommitindex() const;
  void _internal_set_leadercommitindex(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:RaftNodeRpcProtoc.AppendEntriesArgs)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AppendEntriesArgs& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::RaftNodeRpcProtoc::LogEntry > entries_;
    ::int64_t curterm_;
    ::int64_t leaderid_;
    ::int64_t prevlogindex_;
    ::int64_t prevlogterm_;
    ::int64_t leadercommitindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5fnode_5frpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AppendEntriesArgs_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LogEntry

// bytes Command = 1;
inline void LogEntry::clear_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LogEntry::command() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.LogEntry.Command)
  return _internal_command();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void LogEntry::set_command(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.command_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.LogEntry.Command)
}
inline std::string* PROTOBUF_NONNULL LogEntry::mutable_command()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:RaftNodeRpcProtoc.LogEntry.Command)
  return _s;
}
inline const std::string& LogEntry::_internal_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.command_.Get();
}
inline void LogEntry::_internal_set_command(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.command_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL LogEntry::_internal_mutable_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.command_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE LogEntry::release_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RaftNodeRpcProtoc.LogEntry.Command)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.command_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.command_.Set("", GetArena());
  }
  return released;
}
inline void LogEntry::set_allocated_command(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.command_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RaftNodeRpcProtoc.LogEntry.Command)
}

// int64 LogIndex = 2;
inline void LogEntry::clear_logindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logindex_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t LogEntry::logindex() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.LogEntry.LogIndex)
  return _internal_logindex();
}
inline void LogEntry::set_logindex(::int64_t value) {
  _internal_set_logindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.LogEntry.LogIndex)
}
inline ::int64_t LogEntry::_internal_logindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.logindex_;
}
inline void LogEntry::_internal_set_logindex(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logindex_ = value;
}

// int64 LogTerm = 3;
inline void LogEntry::clear_logterm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logterm_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t LogEntry::logterm() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.LogEntry.LogTerm)
  return _internal_logterm();
}
inline void LogEntry::set_logterm(::int64_t value) {
  _internal_set_logterm(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.LogEntry.LogTerm)
}
inline ::int64_t LogEntry::_internal_logterm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.logterm_;
}
inline void LogEntry::_internal_set_logterm(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logterm_ = value;
}

// -------------------------------------------------------------------

// AppendEntriesArgs

// int64 CurTerm = 1;
inline void AppendEntriesArgs::clear_curterm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curterm_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t AppendEntriesArgs::curterm() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesArgs.CurTerm)
  return _internal_curterm();
}
inline void AppendEntriesArgs::set_curterm(::int64_t value) {
  _internal_set_curterm(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesArgs.CurTerm)
}
inline ::int64_t AppendEntriesArgs::_internal_curterm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.curterm_;
}
inline void AppendEntriesArgs::_internal_set_curterm(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curterm_ = value;
}

// int64 LeaderId = 2;
inline void AppendEntriesArgs::clear_leaderid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leaderid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t AppendEntriesArgs::leaderid() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesArgs.LeaderId)
  return _internal_leaderid();
}
inline void AppendEntriesArgs::set_leaderid(::int64_t value) {
  _internal_set_leaderid(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesArgs.LeaderId)
}
inline ::int64_t AppendEntriesArgs::_internal_leaderid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leaderid_;
}
inline void AppendEntriesArgs::_internal_set_leaderid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leaderid_ = value;
}

// int64 PrevLogIndex = 3;
inline void AppendEntriesArgs::clear_prevlogindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prevlogindex_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t AppendEntriesArgs::prevlogindex() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesArgs.PrevLogIndex)
  return _internal_prevlogindex();
}
inline void AppendEntriesArgs::set_prevlogindex(::int64_t value) {
  _internal_set_prevlogindex(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesArgs.PrevLogIndex)
}
inline ::int64_t AppendEntriesArgs::_internal_prevlogindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prevlogindex_;
}
inline void AppendEntriesArgs::_internal_set_prevlogindex(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prevlogindex_ = value;
}

// int64 PrevLogTerm = 4;
inline void AppendEntriesArgs::clear_prevlogterm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prevlogterm_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t AppendEntriesArgs::prevlogterm() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesArgs.PrevLogTerm)
  return _internal_prevlogterm();
}
inline void AppendEntriesArgs::set_prevlogterm(::int64_t value) {
  _internal_set_prevlogterm(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesArgs.PrevLogTerm)
}
inline ::int64_t AppendEntriesArgs::_internal_prevlogterm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prevlogterm_;
}
inline void AppendEntriesArgs::_internal_set_prevlogterm(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prevlogterm_ = value;
}

// repeated .RaftNodeRpcProtoc.LogEntry Entries = 5;
inline int AppendEntriesArgs::_internal_entries_size() const {
  return _internal_entries().size();
}
inline int AppendEntriesArgs::entries_size() const {
  return _internal_entries_size();
}
inline void AppendEntriesArgs::clear_entries() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entries_.Clear();
}
inline ::RaftNodeRpcProtoc::LogEntry* PROTOBUF_NONNULL AppendEntriesArgs::mutable_entries(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:RaftNodeRpcProtoc.AppendEntriesArgs.Entries)
  return _internal_mutable_entries()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>* PROTOBUF_NONNULL AppendEntriesArgs::mutable_entries()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:RaftNodeRpcProtoc.AppendEntriesArgs.Entries)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_entries();
}
inline const ::RaftNodeRpcProtoc::LogEntry& AppendEntriesArgs::entries(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesArgs.Entries)
  return _internal_entries().Get(index);
}
inline ::RaftNodeRpcProtoc::LogEntry* PROTOBUF_NONNULL AppendEntriesArgs::add_entries()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::RaftNodeRpcProtoc::LogEntry* _add = _internal_mutable_entries()->Add();
  // @@protoc_insertion_point(field_add:RaftNodeRpcProtoc.AppendEntriesArgs.Entries)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>& AppendEntriesArgs::entries() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:RaftNodeRpcProtoc.AppendEntriesArgs.Entries)
  return _internal_entries();
}
inline const ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>&
AppendEntriesArgs::_internal_entries() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entries_;
}
inline ::google::protobuf::RepeatedPtrField<::RaftNodeRpcProtoc::LogEntry>* PROTOBUF_NONNULL
AppendEntriesArgs::_internal_mutable_entries() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.entries_;
}

// int64 LeaderCommitIndex = 6;
inline void AppendEntriesArgs::clear_leadercommitindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadercommitindex_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int64_t AppendEntriesArgs::leadercommitindex() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesArgs.LeaderCommitIndex)
  return _internal_leadercommitindex();
}
inline void AppendEntriesArgs::set_leadercommitindex(::int64_t value) {
  _internal_set_leadercommitindex(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesArgs.LeaderCommitIndex)
}
inline ::int64_t AppendEntriesArgs::_internal_leadercommitindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leadercommitindex_;
}
inline void AppendEntriesArgs::_internal_set_leadercommitindex(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leadercommitindex_ = value;
}

// -------------------------------------------------------------------

// AppendEntriesReply

// int64 Term = 1;
inline void AppendEntriesReply::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t AppendEntriesReply::term() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesReply.Term)
  return _internal_term();
}
inline void AppendEntriesReply::set_term(::int64_t value) {
  _internal_set_term(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesReply.Term)
}
inline ::int64_t AppendEntriesReply::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void AppendEntriesReply::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// int64 NextIndex = 2;
inline void AppendEntriesReply::clear_nextindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextindex_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t AppendEntriesReply::nextindex() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesReply.NextIndex)
  return _internal_nextindex();
}
inline void AppendEntriesReply::set_nextindex(::int64_t value) {
  _internal_set_nextindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesReply.NextIndex)
}
inline ::int64_t AppendEntriesReply::_internal_nextindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextindex_;
}
inline void AppendEntriesReply::_internal_set_nextindex(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextindex_ = value;
}

// bool Success = 3;
inline void AppendEntriesReply::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool AppendEntriesReply::success() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesReply.Success)
  return _internal_success();
}
inline void AppendEntriesReply::set_success(bool value) {
  _internal_set_success(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesReply.Success)
}
inline bool AppendEntriesReply::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void AppendEntriesReply::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// int64 NodeState = 4;
inline void AppendEntriesReply::clear_nodestate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodestate_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t AppendEntriesReply::nodestate() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.AppendEntriesReply.NodeState)
  return _internal_nodestate();
}
inline void AppendEntriesReply::set_nodestate(::int64_t value) {
  _internal_set_nodestate(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.AppendEntriesReply.NodeState)
}
inline ::int64_t AppendEntriesReply::_internal_nodestate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nodestate_;
}
inline void AppendEntriesReply::_internal_set_nodestate(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodestate_ = value;
}

// -------------------------------------------------------------------

// RequestVoteArgs

// int64 Term = 1;
inline void RequestVoteArgs::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t RequestVoteArgs::term() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteArgs.Term)
  return _internal_term();
}
inline void RequestVoteArgs::set_term(::int64_t value) {
  _internal_set_term(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteArgs.Term)
}
inline ::int64_t RequestVoteArgs::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void RequestVoteArgs::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// int64 CandidateId = 2;
inline void RequestVoteArgs::clear_candidateid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.candidateid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t RequestVoteArgs::candidateid() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteArgs.CandidateId)
  return _internal_candidateid();
}
inline void RequestVoteArgs::set_candidateid(::int64_t value) {
  _internal_set_candidateid(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteArgs.CandidateId)
}
inline ::int64_t RequestVoteArgs::_internal_candidateid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.candidateid_;
}
inline void RequestVoteArgs::_internal_set_candidateid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.candidateid_ = value;
}

// int64 LastLogIndex = 3;
inline void RequestVoteArgs::clear_lastlogindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastlogindex_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t RequestVoteArgs::lastlogindex() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteArgs.LastLogIndex)
  return _internal_lastlogindex();
}
inline void RequestVoteArgs::set_lastlogindex(::int64_t value) {
  _internal_set_lastlogindex(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteArgs.LastLogIndex)
}
inline ::int64_t RequestVoteArgs::_internal_lastlogindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lastlogindex_;
}
inline void RequestVoteArgs::_internal_set_lastlogindex(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastlogindex_ = value;
}

// int64 LastLogTerm = 4;
inline void RequestVoteArgs::clear_lastlogterm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastlogterm_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t RequestVoteArgs::lastlogterm() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteArgs.LastLogTerm)
  return _internal_lastlogterm();
}
inline void RequestVoteArgs::set_lastlogterm(::int64_t value) {
  _internal_set_lastlogterm(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteArgs.LastLogTerm)
}
inline ::int64_t RequestVoteArgs::_internal_lastlogterm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lastlogterm_;
}
inline void RequestVoteArgs::_internal_set_lastlogterm(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastlogterm_ = value;
}

// -------------------------------------------------------------------

// RequestVoteReply

// int64 Term = 1;
inline void RequestVoteReply::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t RequestVoteReply::term() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteReply.Term)
  return _internal_term();
}
inline void RequestVoteReply::set_term(::int64_t value) {
  _internal_set_term(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteReply.Term)
}
inline ::int64_t RequestVoteReply::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void RequestVoteReply::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// bool VoteGranted = 2;
inline void RequestVoteReply::clear_votegranted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.votegranted_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool RequestVoteReply::votegranted() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteReply.VoteGranted)
  return _internal_votegranted();
}
inline void RequestVoteReply::set_votegranted(bool value) {
  _internal_set_votegranted(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteReply.VoteGranted)
}
inline bool RequestVoteReply::_internal_votegranted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.votegranted_;
}
inline void RequestVoteReply::_internal_set_votegranted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.votegranted_ = value;
}

// int64 VoteState = 3;
inline void RequestVoteReply::clear_votestate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.votestate_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t RequestVoteReply::votestate() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.RequestVoteReply.VoteState)
  return _internal_votestate();
}
inline void RequestVoteReply::set_votestate(::int64_t value) {
  _internal_set_votestate(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.RequestVoteReply.VoteState)
}
inline ::int64_t RequestVoteReply::_internal_votestate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.votestate_;
}
inline void RequestVoteReply::_internal_set_votestate(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.votestate_ = value;
}

// -------------------------------------------------------------------

// InstallSnapshotArgs

// int64 Term = 1;
inline void InstallSnapshotArgs::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t InstallSnapshotArgs::term() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotArgs.Term)
  return _internal_term();
}
inline void InstallSnapshotArgs::set_term(::int64_t value) {
  _internal_set_term(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotArgs.Term)
}
inline ::int64_t InstallSnapshotArgs::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void InstallSnapshotArgs::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// int64 LeaderId = 2;
inline void InstallSnapshotArgs::clear_leaderid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leaderid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t InstallSnapshotArgs::leaderid() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotArgs.LeaderId)
  return _internal_leaderid();
}
inline void InstallSnapshotArgs::set_leaderid(::int64_t value) {
  _internal_set_leaderid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotArgs.LeaderId)
}
inline ::int64_t InstallSnapshotArgs::_internal_leaderid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leaderid_;
}
inline void InstallSnapshotArgs::_internal_set_leaderid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leaderid_ = value;
}

// int64 LastIncludedIndex = 4;
inline void InstallSnapshotArgs::clear_lastincludedindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastincludedindex_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t InstallSnapshotArgs::lastincludedindex() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotArgs.LastIncludedIndex)
  return _internal_lastincludedindex();
}
inline void InstallSnapshotArgs::set_lastincludedindex(::int64_t value) {
  _internal_set_lastincludedindex(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotArgs.LastIncludedIndex)
}
inline ::int64_t InstallSnapshotArgs::_internal_lastincludedindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lastincludedindex_;
}
inline void InstallSnapshotArgs::_internal_set_lastincludedindex(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastincludedindex_ = value;
}

// int64 LastIncludedTerm = 5;
inline void InstallSnapshotArgs::clear_lastincludedterm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastincludedterm_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int64_t InstallSnapshotArgs::lastincludedterm() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotArgs.LastIncludedTerm)
  return _internal_lastincludedterm();
}
inline void InstallSnapshotArgs::set_lastincludedterm(::int64_t value) {
  _internal_set_lastincludedterm(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotArgs.LastIncludedTerm)
}
inline ::int64_t InstallSnapshotArgs::_internal_lastincludedterm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lastincludedterm_;
}
inline void InstallSnapshotArgs::_internal_set_lastincludedterm(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lastincludedterm_ = value;
}

// bytes Snapshot = 6;
inline void InstallSnapshotArgs::clear_snapshot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.snapshot_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& InstallSnapshotArgs::snapshot() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotArgs.Snapshot)
  return _internal_snapshot();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InstallSnapshotArgs::set_snapshot(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.snapshot_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotArgs.Snapshot)
}
inline std::string* PROTOBUF_NONNULL InstallSnapshotArgs::mutable_snapshot()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_snapshot();
  // @@protoc_insertion_point(field_mutable:RaftNodeRpcProtoc.InstallSnapshotArgs.Snapshot)
  return _s;
}
inline const std::string& InstallSnapshotArgs::_internal_snapshot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.snapshot_.Get();
}
inline void InstallSnapshotArgs::_internal_set_snapshot(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.snapshot_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL InstallSnapshotArgs::_internal_mutable_snapshot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.snapshot_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE InstallSnapshotArgs::release_snapshot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RaftNodeRpcProtoc.InstallSnapshotArgs.Snapshot)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.snapshot_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.snapshot_.Set("", GetArena());
  }
  return released;
}
inline void InstallSnapshotArgs::set_allocated_snapshot(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.snapshot_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.snapshot_.IsDefault()) {
    _impl_.snapshot_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RaftNodeRpcProtoc.InstallSnapshotArgs.Snapshot)
}

// -------------------------------------------------------------------

// InstallSnapshotReply

// int64 Term = 1;
inline void InstallSnapshotReply::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t InstallSnapshotReply::term() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotReply.Term)
  return _internal_term();
}
inline void InstallSnapshotReply::set_term(::int64_t value) {
  _internal_set_term(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotReply.Term)
}
inline ::int64_t InstallSnapshotReply::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void InstallSnapshotReply::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// bool Success = 2;
inline void InstallSnapshotReply::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool InstallSnapshotReply::success() const {
  // @@protoc_insertion_point(field_get:RaftNodeRpcProtoc.InstallSnapshotReply.Success)
  return _internal_success();
}
inline void InstallSnapshotReply::set_success(bool value) {
  _internal_set_success(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:RaftNodeRpcProtoc.InstallSnapshotReply.Success)
}
inline bool InstallSnapshotReply::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void InstallSnapshotReply::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace RaftNodeRpcProtoc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // raft_5fnode_5frpc_2eproto_2epb_2eh
