// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node_rpc.proto

#include "node_rpc.pb.h"
#include "node_rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace RaftNodeRpcProtoc {

static const char* RaftNodeRpc_method_names[] = {
  "/RaftNodeRpcProtoc.RaftNodeRpc/RequestVote",
  "/RaftNodeRpcProtoc.RaftNodeRpc/AppendEntries",
  "/RaftNodeRpcProtoc.RaftNodeRpc/InstallSnapshot",
};

std::unique_ptr< RaftNodeRpc::Stub> RaftNodeRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftNodeRpc::Stub> stub(new RaftNodeRpc::Stub(channel, options));
  return stub;
}

RaftNodeRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestVote_(RaftNodeRpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AppendEntries_(RaftNodeRpc_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InstallSnapshot_(RaftNodeRpc_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RaftNodeRpc::Stub::RequestVote(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::RequestVoteArgs& request, ::RaftNodeRpcProtoc::RequestVoteReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RaftNodeRpcProtoc::RequestVoteArgs, ::RaftNodeRpcProtoc::RequestVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestVote_, context, request, response);
}

void RaftNodeRpc::Stub::async::RequestVote(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::RequestVoteArgs* request, ::RaftNodeRpcProtoc::RequestVoteReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RaftNodeRpcProtoc::RequestVoteArgs, ::RaftNodeRpcProtoc::RequestVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, std::move(f));
}

void RaftNodeRpc::Stub::async::RequestVote(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::RequestVoteArgs* request, ::RaftNodeRpcProtoc::RequestVoteReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RaftNodeRpcProtoc::RequestVoteReply>* RaftNodeRpc::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RaftNodeRpcProtoc::RequestVoteReply, ::RaftNodeRpcProtoc::RequestVoteArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RaftNodeRpcProtoc::RequestVoteReply>* RaftNodeRpc::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RaftNodeRpc::Stub::AppendEntries(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::AppendEntriesArgs& request, ::RaftNodeRpcProtoc::AppendEntriesReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RaftNodeRpcProtoc::AppendEntriesArgs, ::RaftNodeRpcProtoc::AppendEntriesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AppendEntries_, context, request, response);
}

void RaftNodeRpc::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::AppendEntriesArgs* request, ::RaftNodeRpcProtoc::AppendEntriesReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RaftNodeRpcProtoc::AppendEntriesArgs, ::RaftNodeRpcProtoc::AppendEntriesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, std::move(f));
}

void RaftNodeRpc::Stub::async::AppendEntries(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::AppendEntriesArgs* request, ::RaftNodeRpcProtoc::AppendEntriesReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RaftNodeRpcProtoc::AppendEntriesReply>* RaftNodeRpc::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::AppendEntriesArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RaftNodeRpcProtoc::AppendEntriesReply, ::RaftNodeRpcProtoc::AppendEntriesArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AppendEntries_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RaftNodeRpcProtoc::AppendEntriesReply>* RaftNodeRpc::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::AppendEntriesArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAppendEntriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RaftNodeRpc::Stub::InstallSnapshot(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::InstallSnapshotArgs& request, ::RaftNodeRpcProtoc::InstallSnapshotReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RaftNodeRpcProtoc::InstallSnapshotArgs, ::RaftNodeRpcProtoc::InstallSnapshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InstallSnapshot_, context, request, response);
}

void RaftNodeRpc::Stub::async::InstallSnapshot(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::InstallSnapshotArgs* request, ::RaftNodeRpcProtoc::InstallSnapshotReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RaftNodeRpcProtoc::InstallSnapshotArgs, ::RaftNodeRpcProtoc::InstallSnapshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, request, response, std::move(f));
}

void RaftNodeRpc::Stub::async::InstallSnapshot(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::InstallSnapshotArgs* request, ::RaftNodeRpcProtoc::InstallSnapshotReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RaftNodeRpcProtoc::InstallSnapshotReply>* RaftNodeRpc::Stub::PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::InstallSnapshotArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RaftNodeRpcProtoc::InstallSnapshotReply, ::RaftNodeRpcProtoc::InstallSnapshotArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RaftNodeRpcProtoc::InstallSnapshotReply>* RaftNodeRpc::Stub::AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::RaftNodeRpcProtoc::InstallSnapshotArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInstallSnapshotRaw(context, request, cq);
  result->StartCall();
  return result;
}

RaftNodeRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftNodeRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftNodeRpc::Service, ::RaftNodeRpcProtoc::RequestVoteArgs, ::RaftNodeRpcProtoc::RequestVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftNodeRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RaftNodeRpcProtoc::RequestVoteArgs* req,
             ::RaftNodeRpcProtoc::RequestVoteReply* resp) {
               return service->RequestVote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftNodeRpc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftNodeRpc::Service, ::RaftNodeRpcProtoc::AppendEntriesArgs, ::RaftNodeRpcProtoc::AppendEntriesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftNodeRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RaftNodeRpcProtoc::AppendEntriesArgs* req,
             ::RaftNodeRpcProtoc::AppendEntriesReply* resp) {
               return service->AppendEntries(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftNodeRpc_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftNodeRpc::Service, ::RaftNodeRpcProtoc::InstallSnapshotArgs, ::RaftNodeRpcProtoc::InstallSnapshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftNodeRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RaftNodeRpcProtoc::InstallSnapshotArgs* req,
             ::RaftNodeRpcProtoc::InstallSnapshotReply* resp) {
               return service->InstallSnapshot(ctx, req, resp);
             }, this)));
}

RaftNodeRpc::Service::~Service() {
}

::grpc::Status RaftNodeRpc::Service::RequestVote(::grpc::ServerContext* context, const ::RaftNodeRpcProtoc::RequestVoteArgs* request, ::RaftNodeRpcProtoc::RequestVoteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftNodeRpc::Service::AppendEntries(::grpc::ServerContext* context, const ::RaftNodeRpcProtoc::AppendEntriesArgs* request, ::RaftNodeRpcProtoc::AppendEntriesReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftNodeRpc::Service::InstallSnapshot(::grpc::ServerContext* context, const ::RaftNodeRpcProtoc::InstallSnapshotArgs* request, ::RaftNodeRpcProtoc::InstallSnapshotReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace RaftNodeRpcProtoc

